product-name: control-plane
network-properties:
  network:
    name: cp
  other_availability_zones: ${az_configuration}
  singleton_availability_zone:
    name: ${az}
product-properties:
  .properties.uaa_endpoint:
    value: ${uaa_endpoint}
  .properties.credhub_endpoint:
    value: ${credhub_endpoint}
  .properties.plane_endpoint:
    value: ${plane_endpoint}
  .properties.tls:
    value:
      cert_pem: ${tls_cert}
      private_key_pem: ${tls_private_key}
  .properties.local_auth:
    value:
    - username: niall
      password: 
        secret: niall